[package]
name = "projector"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "projector"
path = "src/projector-rust/bin/projector.rs"


[dependencies]
anyhow = "1.0.57"
clap = { version = "4.5.11", features = ["derive"] }
